"""
Briefing formatting utilities.

Provides helpers for rendering structured Signal data into the standardised
CompeteIQ weekly intelligence briefing markdown format.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from datetime import datetime
from typing import Any

from models.schemas import Signal

logger = logging.getLogger(__name__)

# Impact badge mapping for readable output
_IMPACT_BADGE: dict[str, str] = {
    "high": "🔴 HIGH",
    "medium": "🟡 MEDIUM",
    "low": "🟢 LOW",
}


class BriefingFormatter:
    """
    Generates structured markdown briefings from extracted Signal data.

    Separates formatting concerns from the synthesizer LLM call so that
    the final document structure is always consistent regardless of model output.
    """

    @staticmethod
    def format_briefing(
        signals: list[Signal],
        competitors: list[str],
        run_id: str,
        executive_summary: str,
        strategic_implications: list[str],
        signals_to_watch: list[str],
        run_date: datetime | None = None,
    ) -> str:
        """
        Render a full CompeteIQ weekly intelligence briefing in markdown.

        Args:
            signals: All extracted Signal instances for this run.
            competitors: Ordered list of competitors that were monitored.
            run_id: Unique identifier for this pipeline run.
            executive_summary: 2-3 sentence LLM-generated overview.
            strategic_implications: 3-5 bullet points from the LLM.
            signals_to_watch: 2-3 developing situations to monitor.
            run_date: Date/time of the run; defaults to now (UTC).

        Returns:
            A fully rendered markdown string.
        """
        date_str = (run_date or datetime.utcnow()).strftime("%B %d, %Y")
        competitors_str = ", ".join(competitors)
        signal_count = len(signals)

        # Group signals by competitor
        by_competitor: dict[str, list[Signal]] = defaultdict(list)
        for sig in signals:
            by_competitor[sig.competitor].append(sig)

        # Sort each competitor's signals by impact (high → medium → low)
        _impact_order = {"high": 0, "medium": 1, "low": 2}
        for comp_signals in by_competitor.values():
            comp_signals.sort(key=lambda s: _impact_order.get(s.impact_assessment, 3))

        lines: list[str] = []

        # Header
        lines += [
            "## CompeteIQ Weekly Intelligence Briefing",
            "",
            f"**Run Date:** {date_str}  ",
            f"**Run ID:** `{run_id}`  ",
            f"**Competitors Monitored:** {competitors_str}  ",
            f"**Signals Detected:** {signal_count}",
            "",
            "---",
            "",
        ]

        # Executive Summary
        lines += [
            "### Executive Summary",
            "",
            executive_summary,
            "",
            "---",
            "",
        ]

        # Key Developments by Competitor
        lines += ["### Key Developments by Competitor", ""]
        if not by_competitor:
            lines.append("*No significant developments detected this week.*")
            lines.append("")
        else:
            for competitor in competitors:
                comp_signals = by_competitor.get(competitor, [])
                if not comp_signals:
                    continue
                lines.append(f"#### {competitor}")
                lines.append("")
                for sig in comp_signals:
                    badge = _IMPACT_BADGE.get(sig.impact_assessment, sig.impact_assessment.upper())
                    signal_label = sig.signal_type.replace("_", " ").title()
                    lines.append(
                        f"- **{signal_label}**: {sig.title} — {sig.summary} "
                        f"[Impact: {badge}]"
                    )
                lines.append("")

        lines += ["---", ""]

        # Strategic Implications
        lines += ["### Strategic Implications", ""]
        for point in strategic_implications:
            bullet = point.lstrip("- •").strip()
            lines.append(f"- {bullet}")
        lines += ["", "---", ""]

        # Signals to Watch
        lines += ["### Signals to Watch", ""]
        for item in signals_to_watch:
            watch = item.lstrip("- •").strip()
            lines.append(f"- {watch}")
        lines += ["", "---", ""]

        # Footer
        lines += [
            f"*Generated by CompeteIQ • Run ID: `{run_id}` • {date_str}*",
            "",
        ]

        return "\n".join(lines)

    @staticmethod
    def signals_to_context_block(signals: list[Signal]) -> str:
        """
        Render signals as a compact text block for LLM prompt injection.

        Args:
            signals: List of Signal instances to render.

        Returns:
            A compact plain-text listing of all signals.
        """
        if not signals:
            return "No signals available."

        parts: list[str] = []
        for i, sig in enumerate(signals, start=1):
            parts.append(
                f"{i}. [{sig.competitor}] {sig.signal_type.upper()}: "
                f"{sig.title} (Impact: {sig.impact_assessment}, "
                f"Confidence: {sig.confidence:.0%})\n"
                f"   {sig.summary}"
            )
        return "\n\n".join(parts)
